from datetime import datetime

# quote generator stores and produces different quotes based on the unique date
class quote_generator:
    def __init__(self, autorun=True):
        # Set the date when the object is created updated in update if the day changes while the progam is running.
        self.date = datetime.today().strftime("%d %m %Y")
        self.autorun = autorun or True
        # Autorun is automically true runs update
        if autorun:
            self.update()
        # if update fails returns data which can be used.
        else: self.QotD = ["If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"]


    # Stores a list of lists [[quote, author]] 366 different quotes
    # Note not all the quotes have been vetted at this time 11/12/25
    def quote_list(self):
        return [
    # Stoics
    ["Waste no more time arguing what a good man should be. Be one.", "Marcus Aurelius"],
    ["We suffer more often in imagination than in reality.", "Seneca"],
    ["He who fears death will never do anything worthy of a living man.", "Seneca"],
    ["Man conquers the world by conquering himself.", "Zeno of Citium"],
    ["It is not things themselves that disturb us, but our opinions about them.", "Epictetus"],
    ["Luck is what happens when preparation meets opportunity.", "Seneca"],
    ["The best revenge is not to be like your enemy.", "Marcus Aurelius"],
    ["If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"],
    ["Wealth consists not in having great possessions, but in having few wants.", "Epictetus"],
    ["He suffers more than necessary, who suffers before it is necessary.", "Seneca"],
    ["First say to yourself what you would be; and then do what you have to do.", "Epictetus"],
    ["It is the power of the mind to be unconquerable.", "Seneca"],
    ["To be calm is the highest achievement of the self.", "Zen proverb"],
    ["No man is free who is not master of himself.", "Epictetus"],
    ["The whole future lies in uncertainty: live immediately.", "Seneca"],
    ["The universe is change; our life is what our thoughts make it.", "Marcus Aurelius"],
    ["Don't explain your philosophy. Embody it.", "Epictetus"],
    ["Difficulties strengthen the mind, as labor does the body.", "Seneca"],
    ["Fate leads the willing, and drags the unwilling.", "Cleanthes"],
    ["To bear trials with a calm mind robs misfortune of its strength.", "Seneca"],
    ["A gem cannot be polished without friction, nor a man perfected without trials.", "Seneca"],
    ["What we fear doing most is usually what we most need to do.", "Seneca"],
    ["He who laughs at himself never runs out of things to laugh at.", "Epictetus"],
    ["Control thy passions lest they take vengeance on thee.", "Epictetus"],
    ["You could leave life right now. Let that determine what you do and say and think.", "Marcus Aurelius"],
    ["The soul becomes dyed with the color of its thoughts.", "Marcus Aurelius"],
    ["No man was ever wise by chance.", "Seneca"],
    ["A man’s worth is no greater than the worth of his ambitions.", "Marcus Aurelius"],
    ["The obstacle is the way.", "Marcus Aurelius"],
    ["The wise man is invincible if he does not fight battles he cannot win.", "Seneca"],
    ["Sometimes even to live is an act of courage.", "Seneca"],
    ["If you want to improve, be content to be thought foolish and stupid.", "Epictetus"],
    ["Make the mind tougher by exposing it to adversity.", "Marcus Aurelius"],
    ["It is impossible for a man to learn what he thinks he already knows.", "Epictetus"],
    ["Happiness and freedom begin with a clear understanding of one principle: some things are within our control, and some things are not.", "Epictetus"],
    ["Don't promise yourself tomorrow. Act now.", "Seneca"],
    ["Time is a created thing. To say 'I don’t have time' is to say 'I don’t want to.'", "Lao Tzu"],
    ["To the wise, life is a problem; to the fool, a solution.", "Marcus Aurelius"],
    ["He who has a why to live can bear almost any how.", "Nietzsche"],
    ["Be tolerant with others and strict with yourself.", "Marcus Aurelius"],
    ["Do not act as if you were going to live ten thousand years.", "Marcus Aurelius"],
    ["To enjoy the things we ought and to hate the things we ought has the greatest bearing on excellence of character.", "Aristotle"],
    ["We are what we repeatedly do. Excellence, then, is not an act but a habit.", "Aristotle"],
    ["Pleasure in the job puts perfection in the work.", "Aristotle"],
    ["A fool thinks himself to be wise, but a wise man knows himself to be a fool.", "Shakespeare"],
    ["Be kind, for everyone you meet is fighting a hard battle.", "Plato"],
    ["Courage is knowing what not to fear.", "Plato"],
    ["The unexamined life is not worth living.", "Socrates"],
    ["To find yourself, think for yourself.", "Socrates"],
    ["Let him that would move the world, first move himself.", "Socrates"],
    ["Contentment is natural wealth, luxury is artificial poverty.", "Socrates"],
    ["Man is disturbed not by things, but by the view he takes of them.", "Epictetus"],
    ["He who is brave is free.", "Seneca"],
    ["We live only now. All the rest is beyond our control.", "Marcus Aurelius"],
    ["The more we value things outside our control, the less control we have.", "Epictetus"],
    ["To live happily is an inward power of the soul.", "Marcus Aurelius"],
    ["A ship should not ride on a single anchor, nor life on a single hope.", "Epictetus"],
    ["Do not explain — your friends do not need it, and your enemies will not believe you anyway.", "Elbert Hubbard"],
    ["There is nothing either good or bad, but thinking makes it so.", "Shakespeare"],
    ["He who knows that enough is enough will always have enough.", "Lao Tzu"],
    ["Silence is a source of great strength.", "Lao Tzu"],
    ["Respond intelligently even to unintelligent treatment.", "Lao Tzu"],
    ["The art of living is more like wrestling than dancing.", "Marcus Aurelius"],
    ["Things do not change; we change.", "Thoreau"],
    ["Beware lest you lose the substance by grasping at the shadow.", "Aesop"],
    ["Nothing endures but change.", "Heraclitus"],
    ["Character is destiny.", "Heraclitus"],
    ["Much learning does not teach understanding.", "Heraclitus"],
    ["Great results cannot be achieved at once; and we must be satisfied to advance in life as we walk, step by step.", "Samuel Smiles"],
    ["To be even-minded is the greatest virtue.", "Heraclitus"],
    ["You have power over your mind — not outside events.", "Marcus Aurelius"],
    ["Truth never damages a cause that is just.", "Mahatma Gandhi"],
    ["An unexamined life is not worth living.", "Socrates"],
    ["No one is free who has not obtained mastery of himself.", "Epictetus"],
    ["Peace of mind is not the absence of conflict but the ability to cope with it.", "Unknown"],
    ["He that can have patience can have what he will.", "Benjamin Franklin"],
    ["Energy and persistence conquer all things.", "Benjamin Franklin"],
    ["Be ashamed to die until you have won some victory for humanity.", "Horace Mann"],
    ["To be wrong is nothing, unless you remember it afterward.", "Confucius"],
    ["When anger rises, think of the consequences.", "Confucius"],
    ["Respect yourself and others will respect you.", "Confucius"],
    ["He who learns but does not think, is lost.", "Confucius"],
    ["Ignorance is the night of the mind, but a night without moon and star.", "Confucius"],
    ["Real knowledge is to know the extent of one’s ignorance.", "Confucius"],
    ["Everything has beauty, but not everyone sees it.", "Confucius"],
    ["The superior man is modest in his speech but exceeds in his actions.", "Confucius"],
    ["To see what is right and not do it is want of courage.", "Confucius"],
    ["Life is really simple, but we insist on making it complicated.", "Confucius"],
    ["Act without expectation.", "Lao Tzu"],
    ["Knowing others is intelligence; knowing yourself is true wisdom.", "Lao Tzu"],
    ["He who conquers others is strong; he who conquers himself is mighty.", "Lao Tzu"],
    ["Nature does not hurry, yet everything is accomplished.", "Lao Tzu"],
    ["Do your duty without attachment to results.", "Bhagavad Gita"],
    ["Man’s greatest victory is over himself.", "Plato"],
    ["The mind is not a vessel to be filled but a fire to be kindled.", "Plutarch"],
    ["Be silent, or let thy words be worth more than silence.", "Pythagoras"],
    ["Rest satisfied with doing well, and leave others to talk of you as they please.", "Pythagoras"],
    ["Numbers rule the universe.", "Pythagoras"],
    ["We are what our thoughts have made us; so take care what you think.", "Swami Vivekananda"],
    ["In the end, it is impossible not to become what others believe you are.", "Hesse"],
    ["To know even one life has breathed easier because you have lived—this is to have succeeded.", "Emerson"],
    # Political
    ["The price of freedom is eternal vigilance.", "Thomas Jefferson"],
    ["Injustice anywhere is a threat to justice everywhere.", "Martin Luther King Jr."],
    ["The ignorance of one voter in a democracy impairs the security of all.", "John F. Kennedy"],
    ["Democracy is the worst form of government, except for all the others.", "Winston Churchill"],
    ["The only stable state is the one in which all men are equal before the law.", "Aristotle"],
    ["The foundation of every state is the education of its youth.", "Diogenes"],
    ["A great democracy must be progressive or it will soon cease to be a great democracy.", "Theodore Roosevelt"],
    ["The true administration of justice is the firmest pillar of good government.", "George Washington"],
    ["Liberty consists in the freedom to do everything which injures no one else.", "Jean-Jacques Rousseau"],
    ["The end of law is not to abolish or restrain, but to preserve and enlarge freedom.", "John Locke"],
    ["The will of the people shall be the basis of the authority of government.", "Universal Declaration of Human Rights"],
    ["Government exists to protect us from each other. Where government has gone beyond its limits is in deciding to protect us from ourselves.", "Ronald Reagan"],
    ["The best laws are those which leave the least to the discretion of the judge.", "Aristotle"],
    ["When the people fear the government, there is tyranny; when the government fears the people, there is liberty.", "Thomas Jefferson"],
    ["Good order is the foundation of all good things.", "Edmund Burke"],
    ["Freedom is not worth having if it does not include the freedom to make mistakes.", "Mahatma Gandhi"],
    ["The greatest danger to liberty lies in the insidious encroachment by men of zeal, well-meaning but without understanding.", "Louis Brandeis"],
    ["Those who deny freedom to others deserve it not for themselves.", "Abraham Lincoln"],
    ["A state without the means of some change is without the means of its conservation.", "Edmund Burke"],
    ["Where law ends, tyranny begins.", "John Locke"],
    ["The history of liberty is a history of the limitation of governmental power, not the increase of it.", "Woodrow Wilson"],
    ["Justice is the bond of men in states; the administration of justice is the principle of order in political society.", "Aristotle"],
    ["He who wishes to be obeyed must know how to command.", "Niccolò Machiavelli"],
    ["A wise ruler ought never to keep faith when by doing so it would be against his interest.", "Niccolò Machiavelli"],
    ["The power to tax involves the power to destroy.", "John Marshall"],
    ["No man is good enough to govern another man without that other's consent.", "Abraham Lincoln"],
    ["The most dangerous man to any government is the man who is able to think things out for himself.", "H. L. Mencken"],
    ["To be governed is to be watched, inspected, spied upon, directed, law-driven, numbered, regulated, enrolled.", "Pierre-Joseph Proudhon"],
    ["Public opinion is the real government in a representative democracy.", "Theodore Parker"],
    ["The first method of estimating the intelligence of a ruler is to look at the men he has around him.", "Niccolò Machiavelli"],
    ["The rights of every man are diminished when the rights of one man are threatened.", "John F. Kennedy"],
    ["The power under the Constitution will always be in the people.", "George Washington"],
    ["The spirit of resistance to government is so valuable on certain occasions that I wish it to be always kept alive.", "Thomas Jefferson"],
    ["The government’s first duty is to protect the people, not run their lives.", "Ronald Reagan"],
    ["The liberty of man is in proportion to the security of his property.", "Adam Smith"],
    ["Liberty cannot be preserved without a general knowledge among the people.", "John Adams"],
    ["Men are qualified for civil liberty in exact proportion to their disposition to put moral chains upon their appetites.", "Edmund Burke"],
    ["The law is reason, free from passion.", "Aristotle"],
    ["Justice cannot be for one side alone, but must be for both.", "Eleanor Roosevelt"],
    ["In matters of conscience, the law of the majority has no place.", "Mahatma Gandhi"],
    ["Rebellion to tyrants is obedience to God.", "Benjamin Franklin"],
    ["Power tends to corrupt, and absolute power corrupts absolutely.", "Lord Acton"],
    ["The more corrupt the state, the more numerous the laws.", "Tacitus"],
    ["The state is made for man, not man for the state.", "Albert Einstein"],
    ["It is not by the consolidation or concentration of powers, but by their distribution, that good government is effected.", "Thomas Jefferson"],
    ["The end of democracy and the defeat of the American Revolution will occur when government falls into the hands of lending institutions.", "Thomas Jefferson"],
    ["In necessary things, unity; in doubtful things, liberty; in all things, charity.", "Augustine of Hippo"],
    ["To sin by silence when they should protest makes cowards of men.", "Abraham Lincoln"],
    ["Let justice be done though the heavens fall.", "Lucius Calpurnius Piso"],
    ["The safety of the people shall be the highest law.", "Cicero"],
    ["Freedom suppressed and again regained bites with keener fangs than freedom never endangered.", "Cicero"],
    ["The health of a republic depends on the virtue of its citizens.", "Montesquieu"],
    ["It is the nature of man to rise against oppression.", "Tacitus"],
    ["In a republic, this rule ought to be observed: that the majority should not have the predominant power.", "Cicero"],
    ["When men are pure, laws are useless; when men are corrupt, laws are broken.", "Benjamin Disraeli"],
    ["No man’s life, liberty, or property are safe while the legislature is in session.", "Mark Twain"],
    ["A constitution is the arrangement of magistrates in a state.", "Aristotle"],
    ["Injustice, in the end, produces independence.", "Voltaire"],
    ["Better risk loss of property than loss of liberty.", "John Adams"],
    ["The greatest punishment for those who refuse to govern themselves is to be governed by others.", "Plato"],
    ["Good government is no substitute for self-government.", "Mahatma Gandhi"],
    ["The tyranny of a prince is not so dangerous to the public welfare as the apathy of a citizen.", "Montesquieu"],
    ["A government of laws, and not of men.", "John Adams"],
    ["The welfare of the people is the ultimate law.", "Cicero"],
    ["Justice delayed is justice denied.", "William Gladstone"],
    ["The strength of a nation derives from the integrity of the home.", "Confucius"],
    ["The vote is a power, not a right; its value depends on how it is used.", "John Stuart Mill"],
    ["The state must be just before it is generous.", "Charles de Gaulle"],
    ["It is better to risk saving a guilty man than to condemn an innocent one.", "Voltaire"],
    ["The duty of youth is to challenge corruption.", "Kurt Cobain"],
    ["When you see a good man, imitate him; when you see a bad man, examine yourself.", "Confucius"],
    ["The greatest happiness of the greatest number is the foundation of morals and legislation.", "Jeremy Bentham"],
    ["Where there is no law, there is no freedom.", "John Locke"],
    ["The more laws, the less justice.", "Cicero"],
    ["Eternal vigilance is the price of liberty.", "Wendell Phillips"],
    ["The liberties of none are safe unless the liberties of all are protected.", "William O. Douglas"],
    ["Those who can make you believe absurdities can make you commit atrocities.", "Voltaire"],
    ["The function of freedom is to free someone else.", "Toni Morrison"],
    ["The best government is that which governs least.", "Henry David Thoreau"],
    ["The punishment which the wise suffer who refuse to take part in the government, is to live under the government of worse men.", "Plato"],
    ["A man who stands for nothing will fall for anything.", "Malcolm X"],
    ["Laws grind the poor, and rich men rule the law.", "Oliver Goldsmith"],
    ["No legacy is so rich as honesty.", "William Shakespeare"],
    ["The object of power is power.", "George Orwell"],
    ["Power without a nation’s confidence is nothing.", "Catherine the Great"],
    ["He who allows oppression shares the crime.", "Erasmus"],
    ["The people, and the people alone, are the motive force in the making of world history.", "Mao Zedong"],  # note: historical context, not endorsement
    ["There is nothing more unequal than the equal treatment of unequal people.", "Thomas Jefferson"],
    ["The care of human life and happiness, and not their destruction, is the first and only legitimate object of good government.", "Thomas Jefferson"],
    ["Where there is no vision, the people perish.", "Proverbs 29:18"],
    ["No government can continue good but under the control of the people.", "Thomas Jefferson"],
    ["If men were angels, no government would be necessary.", "James Madison"],
    ["The best defense of democracy is an informed citizenry.", "Thomas Jefferson"],
    ["The test of good government is its aptitude and tendency to produce a good administration.", "James Madison"],
    ["Public virtue cannot exist in a nation without private virtue.", "John Adams"],
    ["There can be no peace without justice, no justice without law, no law without government, and no meaningful government without a moral foundation.", "Unknown"],
    ["Justice is truth in action.", "Joseph Joubert"],
    ["Laws are silent in times of war.", "Cicero"],
    # Meaning of life
    ["The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "Ralph Waldo Emerson"],
    ["Life is really simple, but we insist on making it complicated.", "Confucius"],
    ["The unexamined life is not worth living.", "Socrates"],
    ["Happiness depends upon ourselves.", "Aristotle"],
    ["Man’s main task in life is to give birth to himself.", "Erich Fromm"],
    ["Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"],
    ["It is not length of life, but depth of life.", "Ralph Waldo Emerson"],
    ["Act as if what you do makes a difference. It does.", "William James"],
    ["Life must be understood backward. But it must be lived forward.", "Søren Kierkegaard"],
    ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
    ["Happiness is not an ideal of reason but of imagination.", "Immanuel Kant"],
    ["The goal of life is living in agreement with nature.", "Zeno of Citium"],
    ["Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "Buddha"],
    ["To live is to suffer, to survive is to find some meaning in the suffering.", "Friedrich Nietzsche"],
    ["Your work is to discover your world and then with all your heart give yourself to it.", "Buddha"],
    ["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
    ["Life is a tragedy when seen in close-up, but a comedy in long-shot.", "Charlie Chaplin"],
    ["The meaning of life is to find your gift. The purpose of life is to give it away.", "Pablo Picasso"],
    ["Man is not worried by real problems so much as by his imagined anxieties about real problems.", "Epictetus"],
    ["Happiness is the highest good.", "Aristotle"],
    ["Life isn’t about finding yourself. Life is about creating yourself.", "George Bernard Shaw"],
    ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"],
    ["Do not spoil what you have by desiring what you have not.", "Epicurus"],
    ["Everything has beauty, but not everyone sees it.", "Confucius"],
    ["It is not length of life, but depth of life.", "Ralph Waldo Emerson"],
    ["The art of life is the art of avoiding pain.", "Epicurus"],
    ["Pleasure is the beginning and the end of living happily.", "Epicurus"],
    ["To be idle is a short road to death and to be diligent is a way of life; foolish people are idle, wise people are diligent.", "Buddha"],
    ["Even while they teach, men learn.", "Seneca"],
    ["Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", "Aristotle"],
    ["It is not what we get. But who we become, what we contribute... that gives meaning to our lives.", "Tony Robbins"],
    ["No man ever steps in the same river twice, for it’s not the same river and he’s not the same man.", "Heraclitus"],
    ["An unfulfilled life is an unhappy life.", "Socrates"],
    ["Life is about making an impact, not making an income.", "Kevin Kruse"],
    ["The secret of success is constancy of purpose.", "Benjamin Disraeli"],
    ["Knowing yourself is the beginning of all wisdom.", "Aristotle"],
    ["The good life is one inspired by love and guided by knowledge.", "Bertrand Russell"],
    ["It is not length of life but depth of life that matters.", "Ralph Waldo Emerson"],
    ["To love oneself is the beginning of a lifelong romance.", "Oscar Wilde"],
    ["Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"],
    ["Life is what happens when you’re busy making other plans.", "John Lennon"],
    ["Do not pray for an easy life, pray for the strength to endure a difficult one.", "Bruce Lee"],
    ["Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "Unknown"],
    ["The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"],
    ["Happiness is only real when shared.", "Christopher McCandless"],
    ["Life is a succession of lessons which must be lived to be understood.", "Ralph Waldo Emerson"],
    ["The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", "Eleanor Roosevelt"],
    ["Every man dies. Not every man really lives.", "William Wallace"],
    ["Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"],
    ["We make a living by what we get, but we make a life by what we give.", "Winston Churchill"],
    ["Life is either a daring adventure or nothing at all.", "Helen Keller"],
    ["The meaning of life is to give life meaning.", "Viktor Frankl"],
    ["When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor Frankl"],
    ["Work for a cause, not for applause.", "Unknown"],
    ["Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"],
    ["Do not go gentle into that good night. Rage, rage against the dying of the light.", "Dylan Thomas"],
    ["Everything that irritates us about others can lead us to an understanding of ourselves.", "Carl Jung"],
    ["Life is a question and how we live it is our answer.", "Gary Keller"],
    ["Man suffers only because he takes seriously what the gods made for fun.", "Alan Watts"],
    ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
    ["Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"],
    ["The only impossible journey is the one you never begin.", "Tony Robbins"],
    ["A life without cause is a life without effect.", "Baron de Montesquieu"],
    ["Don’t count the days, make the days count.", "Muhammad Ali"],
    ["Do not wait to strike till the iron is hot; but make it hot by striking.", "William Butler Yeats"],
    ["What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"],
    ["Life is a journey, not a destination.", "Ralph Waldo Emerson"],
    ["The purpose of life is to contribute in some way to making things better.", "Robert F. Kennedy"],
    ["Man is not worried by real problems so much as by his imagined anxieties about real problems.", "Epictetus"],
    ["Life is short, and it is up to you to make it sweet.", "Sarah Louise Delany"],
    ["Do not spoil what you have by desiring what you have not.", "Epicurus"],
    ["Life is about making an impact, not making an income.", "Kevin Kruse"],
    ["Your work is to discover your world and then with all your heart give yourself to it.", "Buddha"],
    ["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
    ["It is not length of life, but depth of life.", "Ralph Waldo Emerson"],
    ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"],
    ["Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", "Aristotle"],
    ["Man’s main task in life is to give birth to himself.", "Erich Fromm"],
    ["Life must be understood backward. But it must be lived forward.", "Søren Kierkegaard"],
    ["An unfulfilled life is an unhappy life.", "Socrates"],
    ["Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"],
    ["In the end, it’s not the years in your life that count. It’s the life in your years.", "Abraham Lincoln"],
    ["Happiness is not something ready-made. It comes from your own actions.", "Dalai Lama"],
    # Inspirational
    ["Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"],
    ["An investment in knowledge pays the best interest.", "Benjamin Franklin"],
    ["The advancement of learning is the guarantee of the progress of society.", "Francis Bacon"],
    ["Science is the great antidote to the poison of enthusiasm and superstition.", "Adam Smith"],
    ["The true measure of any society can be found in how it treats its most vulnerable members.", "Mahatma Gandhi"],
    ["The first duty of a man is to think for himself.", "José Martí"],
    ["He who opens a school door, closes a prison.", "Victor Hugo"],
    ["Civilization is the progress toward a society of privacy.", "Aldous Huxley"],
    ["The greatness of a nation and its moral progress can be judged by the way its animals are treated.", "Mahatma Gandhi"],
    ["Do not follow where the path may lead. Go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"],
    ["Progress is impossible without change, and those who cannot change their minds cannot change anything.", "George Bernard Shaw"],
    ["The best way to find yourself is to lose yourself in the service of others.", "Mahatma Gandhi"],
    ["What we achieve inwardly will change outer reality.", "Plutarch"],
    ["The highest result of education is tolerance.", "Helen Keller"],
    ["Alone we can do so little; together we can do so much.", "Helen Keller"],
    ["The true sign of intelligence is not knowledge but imagination.", "Albert Einstein"],
    ["Do not wait for extraordinary circumstances to do good; try to use ordinary situations.", "Jean de La Bruyère"],
    ["Knowledge is power.", "Francis Bacon"],
    ["Society exists only as a mental concept; in the real world there are only individuals.", "Oscar Wilde"],
    ["The great aim of education is not knowledge but action.", "Herbert Spencer"],
    ["The progress of society depends on the enlightenment of individuals.", "Voltaire"],
    ["A nation that forgets its past has no future.", "Winston Churchill"],
    ["Science and everyday life cannot and should not be separated.", "Rosalind Franklin"],
    ["It is easier to build strong children than to repair broken men.", "Frederick Douglass"],
    ["Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.", "Desmond Tutu"],
    ["Humanity is the true measure of civilization.", "Unknown"],
    ["The first duty of education is to teach self-respect.", "Edward Lee Thorndike"],
    ["Civilization is a race between education and catastrophe.", "H. G. Wells"],
    ["Our task must be to free ourselves by widening our circle of compassion.", "Albert Einstein"],
    ["The greatness of a civilization is measured by the protection of its most vulnerable.", "Unknown"],
    ["Every act of kindness is a step toward a better civilization.", "Unknown"],
    ["A civilization is only as strong as the moral courage of its citizens.", "Unknown"],
    ["The more enlightened a society, the more it invests in the welfare of its people.", "Unknown"],
    ["To improve the world, one must begin with oneself.", "Mahatma Gandhi"],
    ["The goal of humanity is to leave the world a better place than we found it.", "Unknown"],
    ["Knowledge, compassion, and creativity are the pillars of civilization.", "Unknown"],
    ["Education is not the filling of a pail, but the lighting of a fire.", "William Butler Yeats"],
    ["The true measure of civilization is the advancement of human dignity and freedom.", "Unknown"],
    ["All that is valuable in human society depends upon the opportunity for development accorded the individual.", "Albert Einstein"],
    ["The strength of a civilization lies in the education and moral development of its citizens.", "Unknown"],
    ["Peace cannot be kept by force; it can only be achieved by understanding.", "Albert Einstein"],
    ["A society grows great when old men plant trees whose shade they know they shall never sit in.", "Greek proverb"],
    ["Freedom is nothing else but a chance to be better.", "Albert Camus"],
    ["The world is a dangerous place to live; not because of the people who are evil, but because of the people who don’t do anything about it.", "Albert Einstein"],
    ["The welfare of humanity is always the alibi of tyrants.", "Albert Camus"],
    ["Education is the foundation of every civilization.", "Unknown"],
    ["The human spirit must prevail over technology.", "Albert Einstein"],
    ["It is not the creation of wealth that is wrong, but the love of money for its own sake.", "Margaret Thatcher"],
    ["Civilization flourishes when people strive for the common good, not just personal gain.", "Unknown"],
    ["Happiness is only real when shared.", "Christopher McCandless"],
    ["The strength of a nation derives from the integrity of the home.", "Confucius"],
    ["The progress of society depends on justice, freedom, and knowledge.", "Unknown"],
    ["Every generation must improve upon the last to advance civilization.", "Unknown"],
    ["A society improves when individuals improve themselves.", "Confucius"],
    ["Let us remember: One book, one pen, one child, and one teacher can change the world.", "Malala Yousafzai"],
    ["We do not inherit the Earth from our ancestors; we borrow it from our children.", "Native American proverb"],
    ["Do not judge me by my successes, judge me by how many times I fell and got back up again.", "Nelson Mandela"],
    ["The ultimate goal of civilization is to promote wisdom, compassion, and creativity.", "Unknown"],
    ["Human progress is neither automatic nor inevitable. Every step toward justice requires sacrifice, suffering, and struggle.", "Martin Luther King Jr."],
    ["Civilization is measured not by wealth, but by humanity and moral courage.", "Unknown"],
    ["The advancement of humanity depends on the enlightenment of the individual.", "Voltaire"],
    ["A civilized society invests in the welfare and education of all its citizens.", "Unknown"],
    ["Knowledge, virtue, and compassion are the true pillars of civilization.", "Unknown"],
    ["The greatest measure of civilization is how we treat those who cannot defend themselves.", "Unknown"],
    ["To leave the world a better place, one must educate, inspire, and act.", "Unknown"],
    ["The progress of human civilization is the cumulative result of individual virtue and wisdom.", "Unknown"],
    ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
    ["What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"],
    ["Do not wait to strike till the iron is hot; but make it hot by striking.", "William Butler Yeats"],
    ["Success is not final, failure is not fatal: It is the courage to continue that counts.", "Winston Churchill"],
    ["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
    ["The only way to do great work is to love what you do.", "Steve Jobs"],
    ["Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"],
    ["Everything you’ve ever wanted is on the other side of fear.", "George Addair"],
    ["Start where you are. Use what you have. Do what you can.", "Arthur Ashe"],
    ["Act as if what you do makes a difference. It does.", "William James"],
    ["You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"],
    ["Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"],
    ["Do not let what you cannot do interfere with what you can do.", "John Wooden"],
    ["The best way out is always through.", "Robert Frost"],
    ["Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "Christian D. Larson"],
    ["It always seems impossible until it’s done.", "Nelson Mandela"],
    ["Dream big and dare to fail.", "Norman Vaughan"]
    ]

    
    # update checks the date against a stored date to produce a new quote if the day changes.
    def update(self, date_str=None):
        if date_str is None:
            self.date = datetime.today().strftime("%d %m %Y")
        else:
            self.date = date_str
        self.QotD = self.make(self.date)
        return self.QotD


    # make uses a data algorithm to generate an index number for a random quote.
    def make(self, date_str=None):
        # check data is valid
        if date_str is None:
            date_str = self.date
        # Break date into integers
        d, m, y = [int(x) for x in date_str.split()]
        # make date more unique by mulitplying it.
        base = (y * 10000) + (m * 100) + d
        # randomize result with primes
        n = (d * 31 + m * 12 + y * 17 + (d * m * y))
        # modulo by days of the year 
        result = (n + base) % 366 + 1
        # call the index using random number
        quote = self.quote_list()[result]
        return quote
    


